### ISSUE TITLE
Toevoeging van een geboorte datum

### ISSUE THREAD

**Issue by Prolite2003** [fdnd/whois.fdnd.nl#14]
Het zijn fijn zijn als er een mogelijkheid is voor het toevoegen van je geboorte datum zodat daar op gesorteerd kan worden.

Liever geboorte datum dan leeftijd aangezien je vanuit de geboorte datum automatisch de leeftijd kan berekenen.
Het liefst volgens de engelse volgorde 'Maand, Dag, Jaar' aangezien dat het meeste wordt gebruik wereldwijd.
Voor de mensen die liever niet hun geboorte datum neer willen zetten een mogelijk voor '00/00/0000' of 'NVT'.

**Comment by CelinexPutte** [comment]
Graag geboortedatum inderdaad 😊
