### ISSUE TITLE
Toevoeging kleur

### ISSUE THREAD

**Issue by RickVellingaa** [fdnd/whois.fdnd.nl#15]
Favoriete kleur toevoegen aan API

**Comment by ju5tu5** [comment]
Kleur is geimplementeerd als colour en bevat een hexadecimale kleurnotatie zonder alphawaarde. (semi)transparante kleuren kunnen dus niet gebruikt worden.

**Comment by ju5tu5** [comment]
Het formulier kan nu ook omgaan met kleuren!
